mapping = {
        'anger': ['anger', 'angry', 'anger_annoyance', 'resentment'],
        'annoyance': ['annoyance', 'anger_annoyance', 'annoyed'],
        'anticipation': ['anticipation', 'anticipated', 'anticipating', 'negative_anticipation_including_pessimism','positive_anticipation_including_optimism'],
        'anxiety': ['anxious', 'anxiety'],
        'care': ['care', 'caring'],
        'confusion': ['confusion', 'confused', 'surprise_confusion'],
        'contentment': ['contentment', 'content'],
        'desire': ['desire', 'desired', 'longing', 'envy'],
        'disappointment': ['disappointed', 'disappointment', 'sadness_disappointment'],
        'disgust': ['disgust', 'disgusted'],
        'embarrassment': ['embarrassed', 'embarrassment'],
        'excitement': ['excitement', 'excited'],
        'fear': ['fear', 'fearful', 'scare', 'scared', 'shock'],
        'gratitude': ['gratitude', 'grateful'],
        'guilt': ['guilt', 'guilty'],
        'hope': ['hope', 'hopeful'],
        'joy': ['joy', 'joyful', 'happy', 'happiness'],
        'lonely': ['loneliness', 'lonely'],
        'love': ['love', 'love_including_like'],
        'neutral': ['other', 'others', 'neutral'],
        'optimism': ['optimism', 'positive_anticipation_including_optimism'],
        'pride': ['proud', 'pride'],
        'pessimism': ['pessimism', 'negative_anticipation_including_pessimism'],
        'remorse': ['remorse', 'regret'],
        'sadness': ['sad', 'sadness', 'sadness_disappointment'],
        'shame': ['ashamed', 'shame', 'shamed'],
        'surprise': ['surprise', 'surprised', 'surprise_confusion', 'positive_surprise', 'negative_surprise'],
        'trust': ['trust', 'trusting'],
    }